[package]
name = "shell"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "shell"
path = "shell.rs"

[lib]
name = "shell"
path = "shell.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
